#Exercises 12
#**Numpy**


**Exercises1**
*   **Create an 3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.**




In [1]:
import numpy as np

In [2]:
nested_list =[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]],
              [[16,17,18],[19,20,21],[22,23,24],[25,26,27],[28,29,30]],
              [[31,32,33],[34,35,36],[37,38,39],[40,41,42],[43,44,45]],
              [[46,47,48],[49,50,51],[52,53,54],[55,56,57],[58,59,60]]
             ]

In [3]:
arry_3d=np.array(nested_list) 

In [4]:
print(f'Number of dimensions {arry_3d.ndim}')
print(arry_3d.shape)

Number of dimensions 3
(4, 5, 3)


**Exercises 2**


*   **the shape of created array in the exercise 01 to (20, 3) and check the current dimensions!**




In [5]:
arry_2d=np.reshape(arry_3d,(20,3)) # arry_3d.reshape(20,3)

In [6]:
arry_2d.ndim

2

**Exercices 3**

*   **index and print the number 50 from the arr.**



In [7]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) #([
                                                      # [10, 20, 30, 40],
                                                      # [50, 60, 0, 80]
                                                      #]) >=======row 1 column 0

In [8]:
print(arr[1,0])

50


**Exercies 4**

**Change the element datatype of the arr to float!**

In [9]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]],dtype="d") # d= float64

#or arr=arr.astype(float) or arr=np.float64(arr)

In [10]:
print(arr)

[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]


**Exercies 5**

**join arr1 and arr2 into a single array!**

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [14]:
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[1 2 3 4 5 6]


In [15]:
np.stack((arr1,arr2),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
np.stack((arr1,arr2),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])